# IMPORTANT: You must change this name to your own plugin name!
name: SillyFerret
version: 1.0
main: mods.kpw.my_first_plugin.Main # This will be replaced by a random package name
api-version: '1.21'
